# Generated by Django 5.1.4 on 2025-02-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('organization_name', models.CharField(db_column='Organization Name', max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('contact_person_name', models.CharField(blank=True, db_column='Contact Person Name', max_length=255)),
                ('email_address', models.CharField(blank=True, db_column='Email Address', max_length=255, null=True)),
                ('linkedin_id', models.CharField(blank=True, db_column='LinkedIn ID', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usersdetail',
            fields=[
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True)),
                ('user_image', models.BinaryField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('aadhar_card_no', models.BinaryField(blank=True, primary_key=True, serialize=False)),
                ('signature', models.BinaryField(blank=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other'), ('Not Disclosed', 'Choose not to disclose')], default='Not Disclosed')),
                ('contact', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeDetails',
            fields=[
                ('admin_id', models.AutoField(db_column='Admin ID', primary_key=True, serialize=False)),
                ('name_of_admin', models.CharField(blank=True, db_column='Name of Admin', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, db_column='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other'), ('Not Disclosed', 'Choose not to disclose')], db_column='Gender', default='Not Disclosed')),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, db_column='Contact Number', max_length=20)),
                ('email_address_of_admin', models.CharField(blank=True, db_column='Email Address Of Admin', max_length=255, null=True)),
                ('position_or_title', models.CharField(blank=True, db_column='Position or Title', max_length=50, null=True)),
                ('seceretary_name', models.CharField(blank=True, db_column='Seceretary Name', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Phone Number', max_length=20, null=True)),
                ('email_address_of_seceretary', models.CharField(blank=True, db_column='Email Address Of Seceretary', max_length=255, null=True)),
                ('team_member_1_name', models.CharField(blank=True, db_column='Team Member 1 Name', max_length=200)),
                ('contact_number_of_member_1', models.CharField(blank=True, db_column='Contact Number of Member 1', max_length=20, null=True)),
                ('email_address_of_member_1', models.CharField(blank=True, db_column='Email Address of Member 1', max_length=255, null=True)),
                ('team_member_2_name', models.CharField(blank=True, db_column='Team Member 2 Name', max_length=200)),
                ('contact_number_of_member_2', models.CharField(blank=True, db_column='Contact Number of Member 2', max_length=20)),
                ('email_address_of_member_2', models.CharField(blank=True, db_column='Email Address of Member 2', max_length=255)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255)),
                ('institution_name', models.ForeignKey(db_column='Institution Name', on_delete=django.db.models.deletion.CASCADE, to='backapp.organizationdetails')),
            ],
        ),
    ]
