# Generated by Django 5.1.4 on 2025-03-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_remove_administrativedetails_email_address_of_seceretary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedetails',
            name='institution_name',
            field=models.CharField(db_column='Organization Name', max_length=255),
        ),
    ]
