# Generated by Django 5.1.4 on 2025-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0006_alter_administrativedetails_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativedetails',
            name='college_id',
            field=models.CharField(blank=True, db_column='College ID', max_length=255, null=True),
        ),
    ]
